---
- name: "process groups"
  group:
    name: "{{item.name}}"
    state: "{{item.state|default('present')}}"
    gid: "{{item.gid|default(omit)}}"
  loop: "{{sys_user_groups|flatten}}"

- name: "process user accounts"
  include_tasks: "process_user_accounts.yml"
  loop: "{{sys_user_accounts|flatten}}"
