---
- name: "Network | Interface | {{ name }} | Checking if main interface file exists"
  stat:
    path: "{{ file }}"
  register: iface_file_1
  changed_when: false
  check_mode: false
  when: nw.verification.enable

- name: "Network | Interface | {{ name }} | Checking if main interface file changed"
  template:
    src: 'templates/etc/network/interfaces.d/int.j2'
    dest: "{{ file }}"
    owner: 'root'
    group: 'root'
    mode: 0644
  check_mode: true
  register: iface_file_2
  when: nw.verification.enable

- name: "Network | Interface | {{ name }} | Backing-up current config if changed/exists"
  copy:
    src: "{{ file }}"
    remote_src: true
    dest: "{{ nw_hc.network_script_dir }}/backup/{{ file | replace('/', nw_hc.verification.backup_path_separator) }}"
    owner: 'root'
    group: 'root'
    mode: 0644
  when:
    - nw.verification.enable
    - iface_file_1.stat.exists
    - iface_file_2.changed

- name: "Network | Interface | {{ name }} | Backing-up empty file"
  file:
    path: "{{ nw_hc.network_script_dir }}/backup/{{ file | replace('/', nw_hc.verification.backup_path_separator) }}"
    state: touch
    owner: 'root'
    group: 'root'
    mode: 0644
  when:
    - nw.verification.enable
    - not iface_file_1.stat.exists
    - iface_file_2.changed

- name: "Network | Interface | {{ name }} | Copying main interface file"
  template:
    src: 'templates/etc/network/interfaces.d/int.j2'
    dest: "{{ file }}"
    owner: 'root'
    group: 'root'
    mode: 0644
  when: >
    not nw.verification.enable or
    iface_file_2.changed
