---
- name: "Network | Interface | Purge | {{ iface_name }} | Setting vars"
  set_fact:
    file: "/etc/network/interfaces.d/{{ iface_name }}"

- name: "Network | Interface | Purge | {{ iface_name }} | Backing-up current config"
  copy:
    src: "{{ file }}"
    remote_src: true
    dest: "{{ nw_hc.network_script_dir }}/backup/{{ file | replace('/', nw_hc.verification.backup_path_separator) }}"
    owner: 'root'
    group: 'root'
    mode: 0644
  when: nw.verification.enable

- name: "Network | Interface | Purge | {{ iface_name }} | Removing interface file"
  file:
    path: "{{ file }}"
    state: absent

- name: "Network | Interface | Purge | {{ iface_name }} | Removing interface from running-config"
  # is necessary for vlan interfaces and so on
  shell: "ip addr flush {{ iface_name }} & ifdown {{ iface_name }} & udevadm settle & ip link delete {{ iface_name }}"
  ignore_errors: true
  when: "':' not in iface_name"  # else it will kill the main iface when an alias should get deleted..
